import type { Metadata } from "next";
import { Roboto, Kanit } from "next/font/google";
import "./globals.css";
import { Footer } from "./_components/Footer";

import { getSetting } from "./queries/getSettings";
import { Header } from "./_components/Header";

const fontRoboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const fontKanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const getSettingData = await getSetting();

  return (
    <html lang="en">
      <Header />
      <body
        className={`${fontRoboto.variable} ${fontKanit.variable} antialiased`}
      >
        {children}

        <Footer />
      </body>
    </html>
  );
}
